[package]
name = "rede"
version = "0.1.1"

edition.workspace = true

authors.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true

categories = [
  "command-line-utilities",
  "development-tools",
  "web-programming::http-client",
]
description = "CLI tool to run and configure suites of HTTP requests defined in readable files"
documentation = "https://rede.sotoestevez.dev/"
keywords = ["cli", "http", "api", "request"]
readme = "../README.md"

[dependencies]
rede_parser = "0.2.1"
rede_schema = "0.1"

http.workspace = true
log.workspace = true
miette = { workspace = true, features = ["fancy"] }
mime.workspace = true
thiserror.workspace = true

clap = { version = "4.5.4", features = ["derive"] }
duration-str = { version = "0.7.1", default-features = false }
env_logger = "0.11.3"
reqwest = { version = "=0.12.2", features = ["multipart", "stream"] }
tokio = { version = "1.37.0", features = ["fs"] }
url = "2.5.0"
tokio-util = { version = "0.7.10", features = ["codec"] }
console = "0.15.8"
serde_json = "1.0.115"
indicatif = "0.17.8"

[dev-dependencies]
assert_cmd = "2.0.14"
predicates = "3.1.0"
