[http]
method = "GET"
url = "https://dogapi.dog/api/v2/facts"

[headers]
Accept = "application/json"
User-Agent = "rede/v0.2.0"

[query_params]
limit = "{{limit}}"

[input_params]
limit.hint = "Number of facts to retrieve"

[variables]
limit = 3

