[workspace]
members = [
    "bin",
    "parser"
]
resolver = "2"

[workspace.package]
edition = "2021"

authors = [ "SotoEstevez <ricardo@sotoestevez.dev"]
homepage = "TODO"
repository = "https://github.com/kriogenia/rede"
license = "Apache-2.0 OR MIT"

[workspace.dependencies]
