name: Rust CI
permissions:
  contents: read

on:
  pull_request:
    paths:
      - ".github/workflows/ci.yml"
      - "**.rs"
      - "**.toml"
      - "**/Cargo.lock"
  push:
    paths:
      - ".github/workflows/ci.yml"
      - "**.rs"
      - "**.toml"
      - "**/Cargo.lock"

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Run cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Test workspace - No features
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --no-default-features --workspace --exclude rede_placeholders

      - name: Test workspace - All features
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-features --workspace --exclude rede_placeholders

      - name: Test excluded
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: -p rede_placeholders

  lints:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt, clippy
      
      - name: cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: clippy workspace
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all-features --workspace --exclude rede_placeholders -- -D warnings

      - name: clippy - All features
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -p rede_placeholders -- -D warnings
