name: Publish rede

on:
  push:
    tags:
      - 'rede_v*'
  workflow_dispatch:

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable
      - run: cargo publish --token ${CRATES_TOKEN} -p rede
        env:
          CRATES_TOKEN: ${{ secrets.CRATES_TOKEN }}
